name: Build and commit

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit dist if changed
        run: |
          if ! git diff --quiet -- dist; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dist
            git commit -m "build: update dist [skip ci]"
            git push
          else
            echo "No changes in dist"
          fi
